# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddRule.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
class Ui_Add_Dialog(object):
    def setupUi(self, Dialog, ruleDict):
        # ruleDict is used to update rules (If necessary)
        # For adding rules, ruleDict should be None
        Dialog.setObjectName("Dialog")
        Dialog.resize(741, 495)
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 240, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(60, 310, 621, 71))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 220, 54, 12))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(60, 240, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 240, 91, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(180, 220, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(300, 220, 54, 12))
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(440, 240, 101, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(440, 220, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 270, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(60, 290, 54, 12))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 450, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 450, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 54, 12))
        self.label_7.setObjectName("label_7")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(60, 50, 621, 111))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 410, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(60, 190, 54, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(570, 220, 81, 16))
        self.label_9.setObjectName("label_9")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(570, 240, 101, 22))
        self.comboBox_4.setObjectName("comboBox_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "规则对象"))
        self.label_2.setText(_translate("Dialog", "逻辑操作"))
        self.label_3.setText(_translate("Dialog", "值"))
        self.label_4.setText(_translate("Dialog", "作用范围"))
        self.label_5.setText(_translate("Dialog", "多个值请用逗号隔开"))
        self.label_6.setText(_translate("Dialog", "规则描述"))
        self.pushButton.setText(_translate("Dialog", "确定"))
        self.pushButton_2.setText(_translate("Dialog", "取消"))
        self.label_7.setText(_translate("Dialog", "复合规则"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "操作"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "规则对象"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "逻辑操作"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "值"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "作用范围"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "规则描述"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "规则连接符"))
        self.pushButton_3.setText(_translate("Dialog", "插入"))
        self.label_8.setText(_translate("Dialog", "简单规则"))
        self.label_9.setText(_translate("Dialog", "规则连接符"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv) 
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()  
    sys.exit(app.exec_()) 